[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "snipe-giveaway"
source = "."

[[services.volumes]]
name = "data"
mountPath = "/app/data"
